version: '3.7'
services:
  registry:
    image: registry:2.8.2
    ports:
      - 5001:5000
    volumes:
      - ./data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
  registry-web:
    image: hyper/docker-registry-web:v0.1.2
    ports:
      - 8000:8080
    volumes:
      - ./web-config.yml:/conf/config.yml
      
    environment:
      - REGISTRY_URL=http://registry:5000/v2
      - REGISTRY_NAME=localhost:5000

